# #+title: Team 12 Playable Game Submission

Please checkout the ~robust~ tag to evaluate our submission
- We will add this tag for our submission on Friday, March 29th.

Link to project: https://github.com/SongWithoutWords/contagion

* MILESTONE REQUIREMENTS

Requirements marked [X] are requirements we think are fully satisified
Requirements marked [~] are requirements we think are partially satisfied

For this milestone you should have a complete playable game. You should continue to support all features from prior milestones. You should support robust continuous play with no memory leaks, crashes or glitches, and be able to extensive playability testing, alignment with game development plan.

** (75%) Milestone requirements:

- [X] Include complete playable prior-milestone implementation

- [~] Sustain progressive, non-repetitive gameplay for 6min or more including all new features. The game should not terminate early and should allow infinite even if repetitive gameplay
  - Our game does not terminate early, and may support 6 minutes or more of gameplay depending on the initial state, but does not support infinite gameplay because the game is designed with a finite number of entities, to be won or lost within a finite amount of time

- [X] Support real-time response rate (i.e. lag-free input).

- [X] Include proper memory management (no excessive allocation or leaks). The game should not have any undefined behavior, memory leaks or random crashes. The game should not hog memory even after extended play time.

- [X] The game should robustly handle any user input. Unexpected inputs or environment settings should be correctly handled and reported.

- [X] The gameplay should be real-time (no lag). This included improving your collision handling using effective detection strategies. You should support dozens simultaneously moving main or background assets.

- [~] The game should allow for some form of state saving for play “reload”. Users should be able to pause and restart in a graceful (if not perfect) manner.
     - Can play/pause the game but we do not have save/load yet

- [X] The physical effects should be correctly integrated in time and should not be locked to the machine’s speed by correctly handling the simulation time step and integration.

- [X] Stable game code supporting continuing execution and graceful termination.

** (25%) Creative:
You should implement one or more additional creative elements. These can include additional assets, rendering effects, complex gameplay logic, or pre-emptive implementation of one or more features from subsequent milestones.


* Features completed this milestone

** Camera features
- Finished camera panning by clicking and dragging with the middle mouse button
- Improved camera zoom rate
- Added world border bounds to wasd movement
- Made zooming allowable within world borders only
- Added fullscreen option in main menu and toggable fullscreen mode
- Added camera movement when mouse touches edge of screen in fullscreen mode and bounded it within world borders

** Gameplay features
- Added map boundary
- Added health system (previously a single gunshot was lethal)
- Added gradual infection system (previously zombies infected people immediately, now the infection grows over time)
- Added a new, more powerful police type armed with an automatic weapon (as opposed to a handgun)
- Added new zombie random-walk/roaming behaviour
- WIP new hand-to-hand/melee combat system
  - Zombies claw at humans to spread infection rather than just spreading infection by bumping into them

** Graphics features
- Can now render arbitrary, convex polygons as buildings

** Textures created
- Awesome new background texture for the main menu
- New building texture
- New ground texture
  - It's darker than the old one, so it contrasts better with other sprites, especially bullets and bullet casings which are small and fast moving
- New out-of-bounds texture
- New map boundary texture

** UI features
- Finished implementation of game-over screen, for both victory and defeat
  - Can close the program, return to the main menu, or launch a new game from this screen

* Bugs fixed
- Bug that caused the game to unpause when paused using the mouse
- Bug that prevented cops from running out of ammo and needing to reload

